export class DocumentFolder {
  public static documentTypes = [
        { id: 1, value: 'Copy of Id or smartcard' },
        { id: 2, value: 'Copy of passport' },
        { id: 3, value: 'Power of attorney' },
        { id: 4, value: 'Various certificates' },
        { id: 5, value: 'Employment certificate' },
        { id: 6, value: 'Cover Letter' },
        { id: 7, value: 'Payslips' },
        { id: 8, value: 'Ambulance records' },
        { id: 9, value: 'RAF4 Serious Injury Assessment Report' },
        { id: 10, value: 'RAF1 Statutory medical report' },
        { id: 11, value: 'Narrative Test' },
        { id: 12, value: 'Affidavit' },
        { id: 13, value: 'Radiology report' },
        { id: 14, value: 'Supplementary Medico Legal Report Orthopaedic surgeon' },
        { id: 15, value: 'Referral letter' },
        { id: 16, value: 'Hospital records' },
        { id: 17, value: 'Consultation notes' },
        { id: 18, value: 'Medico Legal Report Industrial Psychologist' },
        { id: 19, value: 'Medico Legal Report Clinical Psychologist' },
        { id: 20, value: 'Medico Legal Report Neurosurgeon' },
        { id: 21, value: 'Medico Legal Report Plastic surgeon' },
        { id: 22, value: 'Medico Legal Report Urologist' },
        { id: 23, value: 'Medico Legal Report Ophthalmologist' },
        { id: 24, value: 'Medico Legal Report Orthopedic Surgeon' },
        { id: 25, value: 'Medico Legal Report Biokineticist' },
        { id: 26, value: 'Medico Legal Report Speech and Language Therapist' },
        { id: 27, value: 'Clinical notes' },
        { id: 28, value: 'First medical report' },
        { id: 29, value: 'Progress medical report' },
        { id: 30, value: 'Final medical Report' },
        { id: 31, value: 'Sick Report' }
    ];
}
